ingestion:
  test_size: 0.25

validation:
  fail_on_extra_columns: true
  max_duplicate_ratio: 0.01

preprocessing:
  apply_smoten: false

model_evaluation:
  mlflow:
    enabled: true
    tracking_uri: http://uat.mlflow.beazley.com

model_registration:
  mlflow:
    enabled: true
    tracking_uri: http://uat.mlflow.beazley.com

model_promotion:
  mlflow:
    enabled: true
    tracking_uri: http://uat.mlflow.beazley.com

