number_of_columns: 39
target_column: fraud_reported
columns:
  - months_as_customer
  - age
  - policy_number
  - policy_bind_date
  - policy_state
  - policy_csl
  - policy_deductable
  - policy_annual_premium
  - umbrella_limit
  - insured_zip
  - insured_sex
  - insured_education_level
  - insured_occupation
  - insured_hobbies
  - insured_relationship
  - capital-gains
  - capital-loss
  - incident_date
  - incident_type
  - collision_type
  - incident_severity
  - authorities_contacted
  - incident_state
  - incident_city
  - incident_location
  - incident_hour_of_the_day
  - number_of_vehicles_involved
  - property_damage
  - bodily_injuries
  - witnesses
  - police_report_available
  - total_claim_amount
  - injury_claim
  - property_claim
  - vehicle_claim
  - auto_make
  - auto_model
  - auto_year
  - fraud_reported
numerical_columns:
  - months_as_customer
  - age
  - policy_number
  - policy_deductable
  - policy_annual_premium
  - umbrella_limit
  - insured_zip
  - capital-gains
  - capital-loss
  - incident_hour_of_the_day
  - number_of_vehicles_involved
  - bodily_injuries
  - witnesses
  - total_claim_amount
  - injury_claim
  - property_claim
  - vehicle_claim
  - auto_year
categorical_columns:
  - policy_bind_date
  - policy_state
  - policy_csl
  - insured_sex
  - insured_education_level
  - insured_occupation
  - insured_hobbies
  - insured_relationship
  - incident_date
  - incident_type
  - collision_type
  - incident_severity
  - authorities_contacted
  - incident_state
  - incident_city
  - incident_location
  - property_damage
  - police_report_available
  - auto_make
  - auto_model
  - fraud_reported
